export const PERMISSIONS = {
  DEPARTMENT_VIEW: "department.view",
  DEPARTMENT_CREATE: "department.create",
  DEPARTMENT_UPDATE: "department.update",
  DEPARTMENT_ARCHIVE: "department.archive",

  USER_VIEW: "user.view",
  USER_CREATE: "user.create",
  USER_UPDATE: "user.update",
  USER_SUSPEND: "user.suspend",

  ROLE_VIEW: "role.view",
  ROLE_CREATE: "role.create",
  ROLE_UPDATE: "role.update",

  DASHBOARD_VIEW: "dashboard.view",

  PROJECT_VIEW: "project.view",
  PROJECT_CREATE: "project.create",
  PROJECT_UPDATE: "project.update",
  PROJECT_ARCHIVE: "project.archive",

  TASK_VIEW: "task.view",
  TASK_CREATE: "task.create",
  TASK_UPDATE: "task.update",

  LEAVE_VIEW: "leave.view",
  LEAVE_CREATE: "leave.create",
  LEAVE_APPROVE: "leave.approve",

  ATTENDANCE_VIEW: "attendance.view",
  ATTENDANCE_MARK: "attendance.mark",
  ATTENDANCE_MANAGE: "attendance.manage",

  ANNOUNCEMENT_VIEW: "announcement.view",
  ANNOUNCEMENT_MANAGE: "announcement.manage",

  DISCUSSION_VIEW: "discussion.view",
  DISCUSSION_CREATE: "discussion.create",
  DISCUSSION_PARTICIPATE: "discussion.participate",

  EVENT_VIEW: "event.view",
  EVENT_MANAGE: "event.manage",

  TICKET_VIEW: "ticket.view",
  TICKET_CREATE: "ticket.create",
  TICKET_MANAGE: "ticket.manage",

  SALARY_VIEW: "salary.view",
  SALARY_GENERATE: "salary.generate",

  AUDIT_VIEW: "audit.view",
} as const;

export type PermissionKey = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

export const ALL_PERMISSIONS: PermissionKey[] = Object.values(PERMISSIONS);

export const PERMISSION_GROUPS: Record<string, PermissionKey[]> = {
  Departments: [
    PERMISSIONS.DEPARTMENT_VIEW,
    PERMISSIONS.DEPARTMENT_CREATE,
    PERMISSIONS.DEPARTMENT_UPDATE,
    PERMISSIONS.DEPARTMENT_ARCHIVE,
  ],
  Users: [
    PERMISSIONS.USER_VIEW,
    PERMISSIONS.USER_CREATE,
    PERMISSIONS.USER_UPDATE,
    PERMISSIONS.USER_SUSPEND,
  ],
  Roles: [PERMISSIONS.ROLE_VIEW, PERMISSIONS.ROLE_CREATE, PERMISSIONS.ROLE_UPDATE],
  Dashboard: [PERMISSIONS.DASHBOARD_VIEW],
  Projects: [
    PERMISSIONS.PROJECT_VIEW,
    PERMISSIONS.PROJECT_CREATE,
    PERMISSIONS.PROJECT_UPDATE,
    PERMISSIONS.PROJECT_ARCHIVE,
  ],
  Tasks: [PERMISSIONS.TASK_VIEW, PERMISSIONS.TASK_CREATE, PERMISSIONS.TASK_UPDATE],
  Leaves: [PERMISSIONS.LEAVE_VIEW, PERMISSIONS.LEAVE_CREATE, PERMISSIONS.LEAVE_APPROVE],
  Attendance: [
    PERMISSIONS.ATTENDANCE_VIEW,
    PERMISSIONS.ATTENDANCE_MARK,
    PERMISSIONS.ATTENDANCE_MANAGE,
  ],
  Announcements: [PERMISSIONS.ANNOUNCEMENT_VIEW, PERMISSIONS.ANNOUNCEMENT_MANAGE],
  Discussions: [
    PERMISSIONS.DISCUSSION_VIEW,
    PERMISSIONS.DISCUSSION_CREATE,
    PERMISSIONS.DISCUSSION_PARTICIPATE,
  ],
  Events: [PERMISSIONS.EVENT_VIEW, PERMISSIONS.EVENT_MANAGE],
  Tickets: [PERMISSIONS.TICKET_VIEW, PERMISSIONS.TICKET_CREATE, PERMISSIONS.TICKET_MANAGE],
  Salary: [PERMISSIONS.SALARY_VIEW, PERMISSIONS.SALARY_GENERATE],
  Audit: [PERMISSIONS.AUDIT_VIEW],
};

const EMPLOYEE_BASE: PermissionKey[] = [
  PERMISSIONS.DASHBOARD_VIEW,
  PERMISSIONS.PROJECT_VIEW,
  PERMISSIONS.TASK_VIEW,
  PERMISSIONS.TASK_UPDATE,
  PERMISSIONS.LEAVE_VIEW,
  PERMISSIONS.LEAVE_CREATE,
  PERMISSIONS.ATTENDANCE_VIEW,
  PERMISSIONS.ATTENDANCE_MARK,
  PERMISSIONS.ANNOUNCEMENT_VIEW,
  PERMISSIONS.DISCUSSION_VIEW,
  PERMISSIONS.DISCUSSION_CREATE,
  PERMISSIONS.DISCUSSION_PARTICIPATE,
  PERMISSIONS.EVENT_VIEW,
  PERMISSIONS.TICKET_VIEW,
  PERMISSIONS.TICKET_CREATE,
  PERMISSIONS.SALARY_VIEW,
];

export const DEFAULT_ROLE_PERMISSIONS: Record<string, PermissionKey[]> = {
  super_admin: ALL_PERMISSIONS,
  admin: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.DEPARTMENT_VIEW,
    PERMISSIONS.DEPARTMENT_CREATE,
    PERMISSIONS.DEPARTMENT_UPDATE,
    PERMISSIONS.DEPARTMENT_ARCHIVE,
    PERMISSIONS.USER_VIEW,
    PERMISSIONS.USER_CREATE,
    PERMISSIONS.USER_UPDATE,
    PERMISSIONS.USER_SUSPEND,
    PERMISSIONS.ROLE_VIEW,
    PERMISSIONS.PROJECT_VIEW,
    PERMISSIONS.PROJECT_CREATE,
    PERMISSIONS.PROJECT_UPDATE,
    PERMISSIONS.PROJECT_ARCHIVE,
    PERMISSIONS.TASK_VIEW,
    PERMISSIONS.TASK_CREATE,
    PERMISSIONS.TASK_UPDATE,
    PERMISSIONS.LEAVE_VIEW,
    PERMISSIONS.LEAVE_CREATE,
    PERMISSIONS.LEAVE_APPROVE,
    PERMISSIONS.ATTENDANCE_VIEW,
    PERMISSIONS.ATTENDANCE_MARK,
    PERMISSIONS.ATTENDANCE_MANAGE,
    PERMISSIONS.ANNOUNCEMENT_VIEW,
    PERMISSIONS.ANNOUNCEMENT_MANAGE,
    PERMISSIONS.DISCUSSION_VIEW,
    PERMISSIONS.DISCUSSION_CREATE,
    PERMISSIONS.DISCUSSION_PARTICIPATE,
    PERMISSIONS.EVENT_VIEW,
    PERMISSIONS.EVENT_MANAGE,
    PERMISSIONS.TICKET_VIEW,
    PERMISSIONS.TICKET_CREATE,
    PERMISSIONS.TICKET_MANAGE,
    PERMISSIONS.SALARY_VIEW,
    PERMISSIONS.SALARY_GENERATE,
  ],
  employee: EMPLOYEE_BASE,
  intern: EMPLOYEE_BASE.filter((p) => p !== PERMISSIONS.SALARY_VIEW),
};
