/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthLoginRouteImport } from './routes/_auth.login'
import { Route as AppUsersRouteImport } from './routes/_app.users'
import { Route as AppTasksRouteImport } from './routes/_app.tasks'
import { Route as AppSupportRouteImport } from './routes/_app.support'
import { Route as AppSalarySlipsRouteImport } from './routes/_app.salary-slips'
import { Route as AppRolesRouteImport } from './routes/_app.roles'
import { Route as AppProjectsRouteImport } from './routes/_app.projects'
import { Route as AppProfileRouteImport } from './routes/_app.profile'
import { Route as AppLeaveRequestsRouteImport } from './routes/_app.leave-requests'
import { Route as AppEventsRouteImport } from './routes/_app.events'
import { Route as AppDiscussionsRouteImport } from './routes/_app.discussions'
import { Route as AppDepartmentsRouteImport } from './routes/_app.departments'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppAuditLogsRouteImport } from './routes/_app.audit-logs'
import { Route as AppAttendanceRouteImport } from './routes/_app.attendance'
import { Route as AppAnnouncementsRouteImport } from './routes/_app.announcements'

const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AppUsersRoute = AppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppRoute,
} as any)
const AppTasksRoute = AppTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AppRoute,
} as any)
const AppSupportRoute = AppSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AppRoute,
} as any)
const AppSalarySlipsRoute = AppSalarySlipsRouteImport.update({
  id: '/salary-slips',
  path: '/salary-slips',
  getParentRoute: () => AppRoute,
} as any)
const AppRolesRoute = AppRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsRoute = AppProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppLeaveRequestsRoute = AppLeaveRequestsRouteImport.update({
  id: '/leave-requests',
  path: '/leave-requests',
  getParentRoute: () => AppRoute,
} as any)
const AppEventsRoute = AppEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AppRoute,
} as any)
const AppDiscussionsRoute = AppDiscussionsRouteImport.update({
  id: '/discussions',
  path: '/discussions',
  getParentRoute: () => AppRoute,
} as any)
const AppDepartmentsRoute = AppDepartmentsRouteImport.update({
  id: '/departments',
  path: '/departments',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditLogsRoute = AppAuditLogsRouteImport.update({
  id: '/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => AppRoute,
} as any)
const AppAttendanceRoute = AppAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => AppRoute,
} as any)
const AppAnnouncementsRoute = AppAnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/announcements': typeof AppAnnouncementsRoute
  '/attendance': typeof AppAttendanceRoute
  '/audit-logs': typeof AppAuditLogsRoute
  '/dashboard': typeof AppDashboardRoute
  '/departments': typeof AppDepartmentsRoute
  '/discussions': typeof AppDiscussionsRoute
  '/events': typeof AppEventsRoute
  '/leave-requests': typeof AppLeaveRequestsRoute
  '/profile': typeof AppProfileRoute
  '/projects': typeof AppProjectsRoute
  '/roles': typeof AppRolesRoute
  '/salary-slips': typeof AppSalarySlipsRoute
  '/support': typeof AppSupportRoute
  '/tasks': typeof AppTasksRoute
  '/users': typeof AppUsersRoute
  '/login': typeof AuthLoginRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/announcements': typeof AppAnnouncementsRoute
  '/attendance': typeof AppAttendanceRoute
  '/audit-logs': typeof AppAuditLogsRoute
  '/dashboard': typeof AppDashboardRoute
  '/departments': typeof AppDepartmentsRoute
  '/discussions': typeof AppDiscussionsRoute
  '/events': typeof AppEventsRoute
  '/leave-requests': typeof AppLeaveRequestsRoute
  '/profile': typeof AppProfileRoute
  '/projects': typeof AppProjectsRoute
  '/roles': typeof AppRolesRoute
  '/salary-slips': typeof AppSalarySlipsRoute
  '/support': typeof AppSupportRoute
  '/tasks': typeof AppTasksRoute
  '/users': typeof AppUsersRoute
  '/login': typeof AuthLoginRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/_app/announcements': typeof AppAnnouncementsRoute
  '/_app/attendance': typeof AppAttendanceRoute
  '/_app/audit-logs': typeof AppAuditLogsRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/departments': typeof AppDepartmentsRoute
  '/_app/discussions': typeof AppDiscussionsRoute
  '/_app/events': typeof AppEventsRoute
  '/_app/leave-requests': typeof AppLeaveRequestsRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/projects': typeof AppProjectsRoute
  '/_app/roles': typeof AppRolesRoute
  '/_app/salary-slips': typeof AppSalarySlipsRoute
  '/_app/support': typeof AppSupportRoute
  '/_app/tasks': typeof AppTasksRoute
  '/_app/users': typeof AppUsersRoute
  '/_auth/login': typeof AuthLoginRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/announcements'
    | '/attendance'
    | '/audit-logs'
    | '/dashboard'
    | '/departments'
    | '/discussions'
    | '/events'
    | '/leave-requests'
    | '/profile'
    | '/projects'
    | '/roles'
    | '/salary-slips'
    | '/support'
    | '/tasks'
    | '/users'
    | '/login'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/announcements'
    | '/attendance'
    | '/audit-logs'
    | '/dashboard'
    | '/departments'
    | '/discussions'
    | '/events'
    | '/leave-requests'
    | '/profile'
    | '/projects'
    | '/roles'
    | '/salary-slips'
    | '/support'
    | '/tasks'
    | '/users'
    | '/login'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_auth'
    | '/_app/announcements'
    | '/_app/attendance'
    | '/_app/audit-logs'
    | '/_app/dashboard'
    | '/_app/departments'
    | '/_app/discussions'
    | '/_app/events'
    | '/_app/leave-requests'
    | '/_app/profile'
    | '/_app/projects'
    | '/_app/roles'
    | '/_app/salary-slips'
    | '/_app/support'
    | '/_app/tasks'
    | '/_app/users'
    | '/_auth/login'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_app/users': {
      id: '/_app/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AppUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tasks': {
      id: '/_app/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AppTasksRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/support': {
      id: '/_app/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof AppSupportRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/salary-slips': {
      id: '/_app/salary-slips'
      path: '/salary-slips'
      fullPath: '/salary-slips'
      preLoaderRoute: typeof AppSalarySlipsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/roles': {
      id: '/_app/roles'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof AppRolesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects': {
      id: '/_app/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AppProjectsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/leave-requests': {
      id: '/_app/leave-requests'
      path: '/leave-requests'
      fullPath: '/leave-requests'
      preLoaderRoute: typeof AppLeaveRequestsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/events': {
      id: '/_app/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof AppEventsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/discussions': {
      id: '/_app/discussions'
      path: '/discussions'
      fullPath: '/discussions'
      preLoaderRoute: typeof AppDiscussionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/departments': {
      id: '/_app/departments'
      path: '/departments'
      fullPath: '/departments'
      preLoaderRoute: typeof AppDepartmentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/audit-logs': {
      id: '/_app/audit-logs'
      path: '/audit-logs'
      fullPath: '/audit-logs'
      preLoaderRoute: typeof AppAuditLogsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/attendance': {
      id: '/_app/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AppAttendanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/announcements': {
      id: '/_app/announcements'
      path: '/announcements'
      fullPath: '/announcements'
      preLoaderRoute: typeof AppAnnouncementsRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAnnouncementsRoute: typeof AppAnnouncementsRoute
  AppAttendanceRoute: typeof AppAttendanceRoute
  AppAuditLogsRoute: typeof AppAuditLogsRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppDepartmentsRoute: typeof AppDepartmentsRoute
  AppDiscussionsRoute: typeof AppDiscussionsRoute
  AppEventsRoute: typeof AppEventsRoute
  AppLeaveRequestsRoute: typeof AppLeaveRequestsRoute
  AppProfileRoute: typeof AppProfileRoute
  AppProjectsRoute: typeof AppProjectsRoute
  AppRolesRoute: typeof AppRolesRoute
  AppSalarySlipsRoute: typeof AppSalarySlipsRoute
  AppSupportRoute: typeof AppSupportRoute
  AppTasksRoute: typeof AppTasksRoute
  AppUsersRoute: typeof AppUsersRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAnnouncementsRoute: AppAnnouncementsRoute,
  AppAttendanceRoute: AppAttendanceRoute,
  AppAuditLogsRoute: AppAuditLogsRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppDepartmentsRoute: AppDepartmentsRoute,
  AppDiscussionsRoute: AppDiscussionsRoute,
  AppEventsRoute: AppEventsRoute,
  AppLeaveRequestsRoute: AppLeaveRequestsRoute,
  AppProfileRoute: AppProfileRoute,
  AppProjectsRoute: AppProjectsRoute,
  AppRolesRoute: AppRolesRoute,
  AppSalarySlipsRoute: AppSalarySlipsRoute,
  AppSupportRoute: AppSupportRoute,
  AppTasksRoute: AppTasksRoute,
  AppUsersRoute: AppUsersRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
